### ISSUE TITLE
p'tites questions

### ISSUE THREAD

**Issue by j2l** [jmfriedt/passive_radar#1]
Bonjour,
Je me permet de vous écrire en français pour m'expliquer au mieux et je suis très content de voir que vous êtes aussi français ;)
il n'y a pas de mail dans votre profil github.

Je cherche à avoir un moyen de détecter les petits bateaux la nuit (ceux sans AIS mais avec réflecteur radar) devant moi à une distance d'au moins 1NM (1.852km). C'est quand on avance de nuit avec visibilité faible.
Un radar commercial coûte trop cher, je ne suis pas pro, juste plaisancier et les longues distances induisent des prises de quart avec des potes, des non professionnels quoi :smile: 

Est-ce que vous pourriez me dire si vous voyez une solution pour mon besoin avec les 2 petits récepteurs et les antennes de vos tests  ? 
J'ai vu que vous détectez les gros navires sur la vidéo de 2018 mais qu'en est-il des navires plus petits à 1NM de distance ?

Faut-il que l'antenne de référence pointe absolument fixement sur l'émetteur sans écart ? Ce qui induit que ça ne fonctionnerait pas sur un bateau en mouvement, il y aurait toujours une vaguelette ou un peu de vent pour la désorienter.

Merci beaucoup et à bientôt !

**Comment by jmfriedt** [comment]
Nous avons etudie' l'utilisation de RADAR passif pour la detection automatique d'aeronefs au dessus d'un LiDAR dans https://www.researchgate.net/publication/331929425_RADAR_passif_pour_la_securite_d%27operation_d%27un_LiDAR et il faut bien avouer que la robustesse fut decevante. Une source "puissante" telle qu'une antenne de television terrestre illumine de facon isotrope l'espace donc pas de directivite' necessaire, mais pour le RADAR passif il faut que l'antenne de reference vise cette source (sur un objet mobile tel qu'un bateau, pas forcement simple) et l'antenne de mesure vise la cible (peut etre une antenne de grande ouverture angulaire pour observer un grand champ, mais pas en direction de la source). Je crains que l'application ne soit trop specifique pour etre applicable dans votre contexte, mais je serai ravi de developper si vous le desirez (friedtj@free.fr)

**Comment by j2l** [comment]
Oui, je vois le problème. C'est ce que je pensais sur la visée de la source. Bon, tant pis. 
Merci beaucoup pour ces précisions !
