### ISSUE TITLE
Specifying Range and Other Variables

### ISSUE THREAD

**Issue by ss32** [jmfriedt/passive_radar#2]
I would like to change the maximum range in the plots but where the value of 12km is calculated is not clear. I see it is a function of `x`  where `x` is the correlation between `ref` and `mes`, but how the value of 12 comes out of that is unclear.

```octave
  for fd=freq
     mesdop=mes.*exp(j*2*pi*fd*disc_time);
     x=abs(xcorr(ref,mesdop,2048));
     rangedop(:,m)=x(2048-20:2048+150-20);
     m=m+1;
  end
```

Also on [line 49](https://github.com/jmfriedt/passive_radar/blob/ab0c36bd9de34e81eee7924534a04d8726f9bc46/171210ship/goship.m#L49) what determines the value `19227738112/4`?  This calculation looks arbitrary but I'm sure it is not.

**Comment by ss32** [comment]
Similarly what is the purpose for iterating over `k1:1008` on [line 43](https://github.com/jmfriedt/passive_radar/blob/ab0c36bd9de34e81eee7924534a04d8726f9bc46/171210ship/goship.m#L43)?

**Comment by jmfriedt** [comment]
> Similarly what is the purpose for iterating over `k=1:1008` on [line 43](https://github.com/jmfriedt/passive_radar/blob/ab0c36bd9de34e81eee7924534a04d8726f9bc46/171210ship/goship.m#L43)?

Getting rid of the beginning of the record when nothing interesting is happening so as to spend processing time on parts of the signal when a target is visible. It could be replaced with a  ``fseek`` I suppose.

**Comment by jmfriedt** [comment]
> I would like to change the maximum range in the plots but where the value of 12km is calculated is not clear. I see it is a function of `x` where `x` is the correlation between `ref` and `mes`, but how the value of 12 comes out of that is unclear.
> 
> ```matlab
>      rangedop(:,m)=x(2048-20:2048+150-20);

The data are sampled at 2.048 MS/s so that the range resolution is 300/2.048/2=73 meters and displaying a range over 170 samples leads to 170*73=12 km. You can change the range by tuning +150. Of course negative range is meaningless but allows for checking that positive range was selected in the right direction, since xcorr(ref,sur) or xcorr(sur,ref) will swap the range axis.

> Also on [line 49](https://github.com/jmfriedt/passive_radar/blob/ab0c36bd9de34e81eee7924534a04d8726f9bc46/171210ship/goship.m#L49) what determines the value `19227738112/4`? This calculation looks arbitrary but I'm sure it is not.

It is the filesize, could be more elegantly be replaced with a ``do ... until``

**Comment by ss32** [comment]
Wonderful, thank you for the quick response!  I will likely submit a PR soon that contains some more descriptive variable names which will make the script easier to tune.
